# Generated by Django 4.0 on 2021-12-21 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_cpf_client_product_name_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cpf_client',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_cliente',
        ),
    ]
