# Generated by Django 4.0 on 2021-12-21 00:23

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_cpf_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cpf_client',
            field=cpf_field.models.CPFField(default=1, max_length=14, verbose_name='Cpf-Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='name_cliente',
            field=models.CharField(default=1, max_length=150, verbose_name='Nome Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
