# Generated by Django 4.0 on 2021-12-21 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_sale_cpf_client_sale_name_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='cpf_client',
        ),
    ]
